Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'lib/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
Metrics/ClassLength:
  CountComments: false
  Max: 99999
Metrics/MethodLength:
  CountComments: false
  Max: 99999
Metrics/LineLength:
  Max: 99999
Metrics/AbcSize:
  Max: 99999