Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'lib/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'test/test_helper.rb'

Metrics/ClassLength:
  CountComments: false
  Max: 99999
Metrics/MethodLength:
  CountComments: false
  Max: 99999
Metrics/LineLength:
  Max: 99999
Metrics/BlockLength:
  Max: 99999
Metrics/AbcSize:
  Max: 99999
Metrics/CyclomaticComplexity:
  Max: 7

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only
