language: ruby
cache: bundler
rvm:
  - 2.2.0

env:
  - DB=mysql
  - DB=sqlite
  - DB=mysql

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test

before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database rails_starter_test'
  - psql -c 'create database rails_starter_test' -U postgres
