language: ruby
cache: bundler

rvm:
  - 2.2.2

env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite
  - DB=mariadb
  # - RAILS_VERSION=4.2.4

bundler_args: --without development

before_script:
  - sleep 15
  - cp config/database.travis.yml config/database.yml
  - cp config/application.example.yml config/application.yml
  - cp config/dropbox.example.yml config/dropbox.yml
  - mysql -e 'create database rails_starter_test'
  - psql -c 'create database rails_starter_test' -U postgres

script:
  # - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rake --trace db:schema:load
  - RAILS_ENV=test bundle exec rake test
  - RAILS_ENV=test bundle exec rake db:seed

matrix:
  allow_failures:
    # - env: DB=sqlite
    - env: DB=mariadb

after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"

branches:
  only:
    - master
    - develop

addons:
  mariadb: '10.0.21'
  code_climate:
    repo_token:
      secure: b6mrCBirtmuHlSsxhKBHEZsbw8StVaaqS7ocB7wYotw+OP8hElkpZb7/Yb7+aGCsClI822n+mhavlGh6QpFlXvT6ptgefyj5Z/Z8HmlOjH8fYmkxYQLTfQ8dzUq6XEngELhHPq9kMskfZgbSH9Q85r/4zapmdE2FJ4dJXNL9XvA=
notifications:
  email: false
  slack:
    secure: C5mVOWuJfFpZwtZQigkATqvgQxXjmo1YnnGRvbsauSpDI9it362L1GsQ50duaSTN//8GfWMqG12bGY4oW8NOgvR/AzrRUD1aAz6ByLaEpb8TKfBbrO5sYSAZn4FRV39aCaAcW6ZuTKJxBmsHo2bdFFpRP07Vmi0bFRRNQO2n+sY=