language: ruby
cache: bundler

rvm:
  - 2.2.2

env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite
  - RAILS_VERSION=5.0.0.beta2

bundler_args: --without development

before_install:
  - export TZ=Europe/Paris

before_script:
  - sleep 5
  - cp config/database.travis.yml config/database.yml
  - cp config/application.example.yml config/application.yml
  - mysql -e 'create database rails_starter_test'
  - psql -c 'create database rails_starter_test' -U postgres

script:
  # - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rake --trace db:schema:load
  - RAILS_ENV=test bundle exec rake test
  - RAILS_ENV=test bundle exec rake db:seed

matrix:
  allow_failures:
    - env: RAILS_VERSION=5.0.0.beta2
  fast_finish: true

after_failure:
  - date
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"

branches:
  only:
    - master
    - develop

addons:
  code_climate:
    repo_token:
      secure: aLmZcxs6oDsqFB8fdivlOsdyWAePxZkdj2vFrd4iS3GwaZz0S6NhJxQzHW+jWAz8L2EEGsFthSBeKzOYR8q/ja7SfowRQ0qLxXY7lVgV4Iv9Y3GiIBjff42e0dCRNeZIVkEBLouLL/GYUp7jdelxlzpibY2t+vt5QtycLiF9+Is=
notifications:
  email: false
  slack:
    secure: HmJCoJ5yy5fv52OZC+1ledyw5PROK2Mdz54mDXg3dAFHe1DjILJhwHUS9eE1say6BUZWr3/ChrO9tJe8l9NK5PLqhPl2sHo2ZHWD78bNAsr1sbD/7wBlPF6ASCDmiZa9pi61YuED36y4bvKMO84tXcmK9Aw65FNTjKpey3/sb4M=