language: ruby
cache: bundler
rvm:
- 2.2.0
env:
- DB=mysql
- DB=postgresql
before_script:
- cp config/database.travis.yml config/database.yml
- cp config/application.example.yml config/application.yml
- mysql -e 'create database rails_starter_test'
- psql -c 'create database rails_starter_test' -U postgres
script:
- RAILS_ENV=test bundle exec rake --trace db:migrate
- RAILS_ENV=test bundle exec rake test
addons:
  code_climate:
    repo_token:
      secure: N7YXFxhySVCwl2+L8IRhrehfVi9juPmovkZCKq91oI7h32BL6SRvGWZbE+e6YEE6GNpxMlnUNz//n5ePn+yEaNdh4K1fJC4z66kLqmQFlt6Ipa0/FdsjsAnxFUERBO/tfAf5pN8mpBKXtHBgPD6FVfuUd+KSnYPU7BgRhtfLmyo=
notifications:
  email: false
  slack:
    secure: C5mVOWuJfFpZwtZQigkATqvgQxXjmo1YnnGRvbsauSpDI9it362L1GsQ50duaSTN//8GfWMqG12bGY4oW8NOgvR/AzrRUD1aAz6ByLaEpb8TKfBbrO5sYSAZn4FRV39aCaAcW6ZuTKJxBmsHo2bdFFpRP07Vmi0bFRRNQO2n+sY=