#
# Application
# =============
# Name
application_name: ~ # ex: my-application

# URL
development: &development_host
  application_host : 'http://localhost:3000'
  application_domain_name: 'localhost:3000'
test: &test
  application_host: ~
  application_domain_name: ~
staging: &staging
  application_host: ~
  application_domain_name: ~
production: &production
  application_host: ~
  application_domain_name: ~
backup: &backup
  application_host: ~
  application_domain_name: ~

# Keys
application_devise_secret_key: ~
application_base_secret_key: ~


#
# Server [Puma]
# ===============
puma_workers: '2'
nginx_use_ssl: 'false'
puma_use_actioncable: 'false'


#
# Database connection
# =====================
db_adapter: 'mysql2' # mysql2, postgresql or sqlite3
db_host: ~
db_username: ~
db_password: ~

development: &development_database
  <<: *development_host
  db_name: ~
test: &test_database
  <<: *test_host
  db_name: ~
staging: &staging_database
  <<: *staging_host
  db_name: ~
  db_username: ~
  db_password: ~
production: &production_database
  <<: *production_host
  db_name: ~
  db_username: ~
  db_password: ~


#
# Omniauth
# ==========
development: &development_omniauth
  <<: *development_database
  facebook_app_id: ~
  facebook_app_secret: ~
  google_app_id: ~
  google_app_secret: ~
test: &test_omniauth
  <<: *test_database
  facebook_app_id: 'test'
  facebook_app_secret: 'test'
  google_app_id: 'test'
  google_app_secret: 'test'
  twitter_app_id: 'test'
  twitter_app_secret: 'test'
staging: &staging_omniauth
  <<: *staging_database
  facebook_app_id: ~
  facebook_app_secret: ~
  google_app_id: ~
  google_app_secret: ~
production: &production_omniauth
  <<: *production_database
  facebook_app_id: ~
  facebook_app_secret: ~
  google_app_id: ~
  google_app_secret: ~


#
# Mapbox
# ========
mapbox_username: ~
mapbox_map_key: ~
mapbox_access_token: ~


#
# Google Map [Autocomplete address]
# ===================================
gmaps_api_key: ~


#
# Google and Bing
# =================
production: &production_seo
  <<: *production_omniauth
  google_analytics_key: ~
  google_site_verification: ~
  bing_site_verification: ~


#
# Froala [ActiveAdmin wysiwyg editor]
# =====================================
froala_key: ~


#
# Capistrano [Deployer]
# =======================
capistrano_repo_url: ~
capistrano_deploy_user: ~
capistrano_server_ip: ~
capistrano_rvm_ruby_version: '2.3.0-preview1' # 2.2.2

staging:
  <<: *staging
  capistrano_deploy_to: ~
production:
  <<: *production
  capistrano_deploy_to: ~


#
# Staging Authentication
# ========================
staging: &staging_htpasswd
  <<: *staging_omniauth
  admin_username: ~
  admin_password: ~
  guest_username: ~
  guest_password: ~


#
# VideoInfo
# ===========
youtube_api_key: ~
vimeo_api_key: ~


#
# Adult module
# ==============
adult_not_validated_popup_redirect_link: 'http://www.lr-agenceweb.fr'


#
# ExceptionNotification [Slack integration]
# ===========================================
exception_notification_slack_webhook_url: ~
exception_notification_slack_channel: '#exceptions'


#
# Backup gem
# ============
backup_parent_class: ~ # Parent class name
production: &production_backup
  <<: *production_seo
  dropbox: # Dropbox [Storage]
    api_key: ~
    api_secret: ~
  slack: # Slack [Notifier]
    webhook_url: ~
    channel: ~
  username: ~
