#
# == Application
#
application_host : http://localhost:3000
domain_name: localhost:3000
application_secret_key_base: ''
devise_secret_key: ''


#
# == Database
#
db_host: ''
db_name: ''
db_username: ''
db_password: ''


#
# == Mapbox
#
mapbox_username: ''
mapbox_map_key: ''
mapbox_access_token: ''


#
# == Twitter
#
twitter_username: ''


#
# == Google and Bing
#
google_analytics_key: ~
google_site_verification: ~
bing_site_verification: ~


#
# == Mandrill (Mail server)
#
mandrill_address: ~
mandrill_port: ~
mandrill_username: ~
mandrill_password: ~