#
# Application
# =============
# Host and domain name
application_name: ~ # ex: my-application
application_host : 'http://localhost:3000'
application_domain_name: 'localhost:3000'

application_host_staging: ~
application_domain_name_staging: ~

application_host_production: ~
application_domain_name_production: ~

application_host_backup: ~
application_domain_name_backup: ~

# Keys
application_devise_secret_key: ~
application_base_secret_key: ~


#
# Server [Puma]
# ===============
puma_workers: '2'
puma_use_actioncable: 'false'
nginx_use_ssl: 'false'


#
# Database connection
# =====================
db_adapter: 'mysql2' # mysql2, postgresql or sqlite3
db_host: ~
db_username: ~
db_password: ~

development: &development
  db_name: ~
test: &test
  db_name: ~
staging: &staging
  db_name: ~
  db_username: ~
  db_password: ~
production: &production
  db_name: ~
  db_username: ~
  db_password: ~


#
# Omniauth
# ==========
development:
  <<: *development
  facebook_app_id: ~
  facebook_app_secret: ~
  google_app_id: ~
  google_app_secret: ~
test:
  <<: *test
  facebook_app_id: 'test'
  facebook_app_secret: 'test'
  google_app_id: 'test'
  google_app_secret: 'test'
  twitter_app_id: 'test'
  twitter_app_secret: 'test'
staging:
  <<: *staging
  facebook_app_id: ~
  facebook_app_secret: ~
  google_app_id: ~
  google_app_secret: ~
production:
  <<: *production
  facebook_app_id: ~
  facebook_app_secret: ~
  google_app_id: ~
  google_app_secret: ~


#
# Mapbox
# ========
mapbox_username: ~
mapbox_map_key: ~
mapbox_access_token: ~


#
# Google Map [Autocomplete address]
# ===================================
gmaps_api_key: ~


#
# Google and Bing
# =================
production:
  <<: *production
  google_analytics_key: ~
  google_site_verification: ~
  bing_site_verification: ~


#
# Froala [ActiveAdmin wysiwyg editor]
# =====================================
froala_key: ~


#
# Capistrano [Deployer]
# =======================
capistrano_repo_url: ~
capistrano_deploy_user: ~
capistrano_server_ip: ~
capistrano_rvm_ruby_version: '2.3.0-preview1' # 2.2.2

staging:
  <<: *staging
  capistrano_deploy_to: ~
production:
  <<: *production
  capistrano_deploy_to: ~


#
# Staging Authentication
# ========================
staging:
  <<: *staging
  admin_username: ~
  admin_password: ~
  guest_username: ~
  guest_password: ~


#
# VideoInfo
# ===========
youtube_api_key: ~
vimeo_api_key: ~


#
# Adult module
# ==============
adult_not_validated_popup_redirect_link: 'http://www.lr-agenceweb.fr'


#
# ExceptionNotification [Slack integration]
# ===========================================
exception_notification_slack_webhook_url: ~
exception_notification_slack_channel: '#exceptions'


#
# Backup gem
# ============
backup_parent_class: ~ # Parent class name
production:
  <<: *production
  dropbox: # Dropbox [Storage]
    api_key: ~
    api_secret: ~
  slack: # Slack [Notifier]
    webhook_url: ~
    channel: ~
  username: ~
