#
# == Application
#
application_host : 'http://localhost:3000'
application_domain_name: 'localhost:3000'
application_name: ~
application_devise_secret_key: ~
application_base_secret_key: ~


#
# == Database
#
db_host: ~
staging:
  db_name: ~
  db_username: ~
  db_password: ~
production:
  db_name: ~
  db_username: ~
  db_password: ~


#
# == Omniauth
#
development:
  facebook_app_id: ~
  facebook_app_secret: ~
  google_app_id: ~
  google_app_secret: ~
staging:
  facebook_app_id: ~
  facebook_app_secret: ~
  google_app_id: ~
  google_app_secret: ~
production:
  facebook_app_id: ~
  facebook_app_secret: ~
  google_app_id: ~
  google_app_secret: ~


#
# == Mapbox
#
mapbox_username: ~
mapbox_map_key: ~
mapbox_access_token: ~


#
# == Google and Bing
#
production:
  google_analytics_key: ~
  google_site_verification: ~
  bing_site_verification: ~


#
# == Mail server
#
mailer_address: ~
mailer_port: ~
mailer_user_name: ~
mailer_password: ~


#
# == Froala [ActiveAdmin wysiwyg editor]
#
froala_key: ~


#
# == Capistrano [Deployer]
#
capistrano_repo_url: ~
capistrano_deploy_user: ~
capistrano_server_ip: ~

staging:
  capistrano_deploy_to: ~
production:
  capistrano_deploy_to: ~


#
# == Staging Authentication
#
staging:
  admin_username: ~
  admin_password: ~
  guest_username: ~
  guest_password: ~


#
# == VideoInfo
#
youtube_api_key: ~
vimeo_api_key: ~


#
# == Misc
#
loader_spinner_img: http://www.salons-sante-autonomie.com/content/themes/ssa/img/assets/spinner.gif


#
# == Adult module
#
adult_not_validated_popup_redirect_link: 'http://www.lr-agenceweb.fr'


#
# == Backup gem
#
production:
  dropbox: # Dropbox [Storage]
    api_key: ~
    api_secret: ~
  slack: # Slack [Notifier]
    webhook_url: ~
    channel: ~
  username: ~